# Generated by Django 5.0.1 on 2026-03-05 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandicapHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('handicap_index', models.DecimalField(decimal_places=1, max_digits=4)),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('rounds_count', models.IntegerField()),
                ('differentials_used', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handicap_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Handicap Histories',
                'ordering': ['-calculation_date'],
            },
        ),
    ]
