# Generated by Django 5.0.1 on 2026-02-25 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fairways_hit', models.IntegerField(default=0)),
                ('greens_in_regulation', models.IntegerField(default=0)),
                ('total_putts', models.IntegerField(default=0)),
                ('eagles', models.IntegerField(default=0)),
                ('birdies', models.IntegerField(default=0)),
                ('pars', models.IntegerField(default=0)),
                ('bogeys', models.IntegerField(default=0)),
                ('double_bogeys', models.IntegerField(default=0)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='rounds.round')),
            ],
            options={
                'verbose_name_plural': 'Stats',
                'ordering': ['-round__date'],
            },
        ),
    ]
