# Generated by Django 5.0.1 on 2026-02-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_api_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
