# Generated by Django 5.0.1 on 2026-05-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_external_api_id_course_last_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetee',
            name='back_course_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='coursetee',
            name='back_slope_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursetee',
            name='front_course_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='coursetee',
            name='front_slope_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
