# Generated by Django 5.0.1 on 2026-02-25 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Total Score'), (1, 'Hole-by-Hole')], default=1)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='courses.course')),
                ('course_tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='courses.coursetee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to=settings.AUTH_USER_MODEL)),
                ('score_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='rounds.scoretype')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RoundScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('net_score', models.IntegerField()),
                ('gross_score', models.IntegerField()),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='rounds.round')),
            ],
            options={
                'ordering': ['-round__date'],
            },
        ),
        migrations.CreateModel(
            name='HoleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField()),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='courses.hole')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_scores', to='rounds.round')),
            ],
            options={
                'ordering': ['round', 'hole__hole_number'],
                'unique_together': {('hole', 'round')},
            },
        ),
    ]
