# Generated by Django 5.0.1 on 2026-02-25 04:15

from django.db import migrations


def populate_score_types(apps, schema_editor):
    ScoreType = apps.get_model('rounds', 'ScoreType')
    ScoreType.objects.get_or_create(type=0)
    ScoreType.objects.get_or_create(type=1)


def reverse_populate_score_types(apps, schema_editor):
    ScoreType = apps.get_model('rounds', 'ScoreType')
    ScoreType.objects.filter(type__in=[0, 1]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_score_types, reverse_populate_score_types),
    ]
