# Generated by Django 5.0.1 on 2026-03-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0002_populate_score_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='holescore',
            name='fairway_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holescore',
            name='gir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holescore',
            name='putts',
            field=models.IntegerField(default=0),
        ),
    ]
