# Generated by Django 5.0.1 on 2026-05-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0003_add_holescore_stats_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='hole_segment',
            field=models.CharField(choices=[('full_18', '18 Holes'), ('front_9', 'Front 9'), ('back_9', 'Back 9')], default='full_18', max_length=10),
        ),
        migrations.AddField(
            model_name='round',
            name='holes_played',
            field=models.IntegerField(default=18),
        ),
    ]
